### ISSUE TITLE
Example app and my app close after printing

### ISSUE THREAD

**Issue by Blackheart8788** [amoLink/bluetooth_print_plus#11]
Good morning,

Thanks for your hard work and this package.

The example app and my personal app close after printing images using ESC or CPCL commands.

I'm testing in different physical devices with Android 10 to 13.

**Comment by amoLink** [comment]
how about TSC command？ Perhaps your printer does not support ESC or CPCL commands, which is causing the issue

**Comment by Blackheart8788** [comment]
I have two different printers. TSC command does not work at all if I use ESC or CPCL commands to print text, qr or bar codes everything works fine. but if I print images after the printer finishes printing both apps close.

**Comment by amoLink** [comment]
I'm not sure why, but I suggest you contact the printer company

**Comment by Blackheart8788** [comment]
The weir thing is that is happening with different printers from different brands.

If you are interested below you can read y debug console output:

`2
I/BluetoothAdapter(26394): STATE_ON
D/BluetoothLeScanner(26394): could not find callback wrapper
2
E/ThreadPoolManager(26394): 
E/BluetoothPort(26394): [ (BluetoothPort.java:142)#OpenPort ] try to open connect printer
I/BluetoothAdapter(26394): cancelDiscovery
2
I/BluetoothAdapter(26394): STATE_ON
D/BluetoothLeScanner(26394): could not find callback wrapper
I/BluetoothSocket(26394): connect() for device 91C1BC_A called by pid: 26394
[log] ********cur device status: 1
D/BluetoothPrintPlusPlugin(26394): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
D/BluetoothSocket(26394): waitSocketSignal read 20 bytes signal ret: 20
D/BluetoothSocket(26394): waitSocketSignal: sig size: 20, remote addr: 91C1BC_AA, channel: 1, status: 0 MaxRxPktSize: 0 MaxTxPktSize: 0
E/BluetoothPort(26394): [ (BluetoothPort.java:78)#Run ] 读数据...
D/BluetoothSocket(26394): read in:  android.net.LocalSocketImpl$SocketInputStream@f1a447 len: 128
I/ViewRootImpl@57a4ee7[MainActivity](26394): ViewPostIme pointer 0
I/ViewRootImpl@57a4ee7[MainActivity](26394): ViewPostIme pointer 1
D/BluetoothSocket(26394): write: android.net.LocalSocketImpl$SocketOutputStream@cdac474 length: 32851
D/BluetoothSocket(26394): write out: android.net.LocalSocketImpl$SocketOutputStream@cdac474 length: 32851
I/System.out(26394): 发送成功
D/BluetoothSocket(26394): read out:  android.net.LocalSocketImpl$SocketInputStream@f1a447 ret: 3
E/BluetoothPort(26394): [ (BluetoothPort.java:80)#Run ] len...3
E/BluetoothPort(26394): [ (BluetoothPort.java:78)#Run ] 读数据...
D/BluetoothSocket(26394): read in:  android.net.LocalSocketImpl$SocketInputStream@f1a447 len: 128
D/AndroidRuntime(26394): Shutting down VM
E/AndroidRuntime(26394): FATAL EXCEPTION: main
E/AndroidRuntime(26394): Process: ca.sdc.sdc_mobile, PID: 26394
E/AndroidRuntime(26394): java.lang.NullPointerException: Attempt to invoke interface method 'void com.gprinter.utils.CallbackListener.onReceive(byte[])' on a null object reference
E/AndroidRuntime(26394): 	at com.gprinter.io.BluetoothPort$IoReader$1.run(BluetoothPort.java:91)
E/AndroidRuntime(26394): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(26394): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26394): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(26394): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(26394): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime(26394): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26394): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime(26394): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process (26394): Sending signal. PID: 26394 SIG: 9
Lost connection to device.

Exited.`
