### ISSUE TITLE
v2.4.2直接连接蓝牙打印机会导致app崩溃

### ISSUE THREAD

**Issue by aaron0713** [amoLink/bluetooth_print_plus#48]
先调用startScan，然后在listener里连接打印机，打印正常。
如果直接从缓存里获取到设备address，（之前没有Scan），创建连接（`BluetoothDevice(_Printer.name!, _Printer.macAddress!)`），会导致app崩溃：
```
E/AndroidRuntime(  930): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(  930): 	at com.example.bluetooth_print_plus.bluetooth_print_plus.BluetoothPrintPlusPlugin$2$1.onSuccess(BluetoothPrintPlusPlugin.java:329)
E/AndroidRuntime(  930): 	at com.gprinter.io.BluetoothPort$3.run(BluetoothPort.java:252)
E/AndroidRuntime(  930): 	at android.os.Handler.handleCallback(Handler.java:836)
E/AndroidRuntime(  930): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(  930): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime(  930): 	at android.app.ActivityThread.main(ActivityThread.java:6367)
E/AndroidRuntime(  930): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  930): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
E/AndroidRuntime(  930): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
Lost connection to device.

Exited.
```

**Comment by amoLink** [comment]
年后修复
